### ISSUE TITLE
[Important] Modelling script error

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group313#52]
The script fails, see error below.

Also, this script needs to include at least one test

```
PS C:\Users\...\DSCI_522_Group313> python src/model.py --source_file_location=data --target_location=results
data
results
Running Support Vector Regressor
Traceback (most recent call last):
  File "src/model.py", line 117, in <module>
    main(opt['--source_file_location'], opt['--target_location'])
  File "src/model.py", line 44, in main
    clf.fit(X_train, y_train.to_numpy().ravel())
  File "C:\Users\...\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 630, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\...\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 230, in indexable
    check_consistent_length(*result)
  File "C:\Users\...\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1755, 3510]
```

**Comment by camadi** [comment]
This issue has been fixed by changing the index to False during saving of preprocessed files.
